steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', '${_DOCKER_REPO}:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '--cache-from', '${_DOCKER_REPO}:latest', '-f', 'Dockerfile', '-t', '${_DOCKER_REPO}:$SHORT_SHA', '-t', '${_DOCKER_REPO}:latest']

images:
- '${_DOCKER_REPO}:$SHORT_SHA'
- '${_DOCKER_REPO}:latest'
