steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --context=dir:///workspace
  - --dockerfile=Dockerfile
  - --build-arg=VERSION=${_BASE_IMAGE_VERSION}
  - --destination=${_DOCKER_REPO}:$SHORT_SHA
  - --destination=${_DOCKER_REPO}:latest
  - --cache=true
  - --cache-ttl=168h

substitutions:
  _BASE_IMAGE_VERSION: '18.1'
